version: '3'

services:
  app1:
    build: .
    environment:
      - APP_NAME=APP1
    ports:
      - "6000:6000"

  app2:
    build: .
    environment:
      - APP_NAME=APP2
    ports:
      - "6002:6000"
  app3:
    build: .
    environment:
      - APP_NAME=APP3
    ports:
      - "6003:6000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3

